### ISSUE TITLE
Relation Creation does not find my first Topic

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group6#207] opened 2016-01-05 18:01 UTC
I logged in as uskudarli
I tried creating a relation between Net Neutrality and Mark Zuckerberg.

First I tried from the "Relations" tab. That offered me a topic and a relation (reason for relation). I don't know what that did. I did not understand the intent either. 

Then I tried to create the relation from the main "Create a Relation" command. This gave me more confidence, since I got two topics to define. Alas, this time it did not find my topic "Net Neutrality", which I did create, as seen below:

![relation creation problem](https://cloud.githubusercontent.com/assets/1347035/12122975/f20ae032-b3e6-11e5-879f-2f4f4c393b13.png)

Just wanted to give some representative data I would be interested in contributing.

**Comment by temelkandaz** [comment] 2016-01-05 23:06
Thank you for reporting the bug. 

2 things were probably causing this bug. One of them was a backend problem which we haven't identified yet and the other was an issue about a jQuery event listener. I changed the event listener and now it finds the topic. You can see below. However this screenshot is taken from the code working on my local server. Once it is online, I will inform you.

![screen shot 2016-01-06 at 00 46 16](https://cloud.githubusercontent.com/assets/12714838/12129879/214d7d3c-b40f-11e5-9cd1-8472acda183f.png)

**Comment by temelkandaz** [comment] 2016-01-06 21:17
New version is online! Please test and close the issue if you think the problem is solved.

**Comment by uskudarli** [comment] 2016-01-06 21:47
:+1: 

Works. 

But, there is a little problem. After I created the relation all the content on the main page disappeared, such as the nodes, etc. 

When I went to Full Screen mode, I saw the nodes and relations again. Looks very nice!

**Closed** 2016-01-06 21:56 UTC
Labels: bug, Priority-High
